/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/3d/scene/main.glb 
*/

import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/main.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="exterior_wheels" position={[2.479, 0.942, 0]} rotation={[-Math.PI / 2, 0, 0]} />
        <group name="Object_6001" position={[0, 0.437, 0.154]} />
        <group name="Object_6002" position={[0, 0.437, 0.154]} />
        <mesh name="int_window_frame" geometry={nodes.int_window_frame.geometry} material={nodes.int_window_frame.material} />
        <mesh name="int_pannels" geometry={nodes.int_pannels.geometry} material={nodes.int_pannels.material} />
        <mesh name="int_pannel" geometry={nodes.int_pannel.geometry} material={nodes.int_pannel.material} position={[0.016, 0, 0]} />
        <mesh name="int_compartments" geometry={nodes.int_compartments.geometry} material={nodes.int_compartments.material} position={[0, 1.4, 0.69]} />
        <mesh name="int_compartments_handles" geometry={nodes.int_compartments_handles.geometry} material={nodes.int_compartments_handles.material} position={[-0.692, 1.83, 0.378]} scale={0.452} />
        <mesh name="int_kitchen_drawer_" geometry={nodes.int_kitchen_drawer_.geometry} material={nodes.int_kitchen_drawer_.material}>
          <mesh name="refrigerator" geometry={nodes.refrigerator.geometry} material={nodes.refrigerator.material} position={[0.775, 0.916, 0.865]} />
        </mesh>
        <mesh name="int_kitchen_pannels" geometry={nodes.int_kitchen_pannels.geometry} material={nodes.int_kitchen_pannels.material} position={[0.61, 0.81, 1.173]} />
        <mesh name="int_kitchen_surfaces" geometry={nodes.int_kitchen_surfaces.geometry} material={nodes.int_kitchen_surfaces.material} position={[0.61, 0.81, 1.173]} />
        <mesh name="int_kitchen_sink" geometry={nodes.int_kitchen_sink.geometry} material={nodes.int_kitchen_sink.material} position={[0.61, 0.81, 1.173]} />
        <mesh name="int_kitchen_cooktop" geometry={nodes.int_kitchen_cooktop.geometry} material={nodes.int_kitchen_cooktop.material} position={[0.041, 1.469, 1.182]} />
        <mesh name="int_kitchen_oven" geometry={nodes.int_kitchen_oven.geometry} material={nodes.int_kitchen_oven.material} position={[-0.072, 1.131, 1.186]} />
        <mesh name="int_air_onditionair" geometry={nodes.int_air_onditionair.geometry} material={nodes.int_air_onditionair.material} position={[-0.016, 1.303, 0.408]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.184, 0.223, 0.223]} />
        <group name="int_termostat" position={[0.718, 1.342, 0.703]} rotation={[0, 0, Math.PI]} scale={-0.249}>
          <mesh name="Cube015" geometry={nodes.Cube015.geometry} material={nodes.Cube015.material} />
          <mesh name="Cube015_1" geometry={nodes.Cube015_1.geometry} material={materials.mat_dark_black} />
          <mesh name="Cube015_2" geometry={nodes.Cube015_2.geometry} material={materials['Material.001']} />
        </group>
        <mesh name="int_maxxair_vent" geometry={nodes.int_maxxair_vent.geometry} material={nodes.int_maxxair_vent.material} position={[0, 1.887, -0.391]} scale={0.268} />
        <group name="ext_maxxhair_vent">
          <mesh name="Plane001" geometry={nodes.Plane001.geometry} material={materials['mat_dark_black.001']} />
          <mesh name="Plane001_1" geometry={nodes.Plane001_1.geometry} material={materials['Material.002']} />
        </group>
        <mesh name="ext_window_frame" geometry={nodes.ext_window_frame.geometry} material={nodes.ext_window_frame.material} />
        <mesh name="ext_window_main" geometry={nodes.ext_window_main.geometry} material={nodes.ext_window_main.material} />
        <mesh name="exterior_chassis_" geometry={nodes.exterior_chassis_.geometry} material={nodes.exterior_chassis_.material} position={[0.63, 1.401, 0.689]} />
        <mesh name="ext_gas_cylinder_housing" geometry={nodes.ext_gas_cylinder_housing.geometry} material={nodes.ext_gas_cylinder_housing.material} />
        <mesh name="ext_door_inner_l" geometry={nodes.ext_door_inner_l.geometry} material={nodes.ext_door_inner_l.material} position={[-1.403, 1.303, -1.065]} rotation={[-Math.PI, 1.202, -Math.PI]} />
        <mesh name="ext_door_window_l" geometry={nodes.ext_door_window_l.geometry} material={nodes.ext_door_window_l.material} position={[-1.617, 1.697, -1.171]} rotation={[-Math.PI, 1.202, -Math.PI]} />
        <mesh name="ext_door_frame_l" geometry={nodes.ext_door_frame_l.geometry} material={nodes.ext_door_frame_l.material} position={[-1.403, 1.303, -1.065]} rotation={[-Math.PI, 1.202, -Math.PI]} />
        <mesh name="ext-door-galley" geometry={nodes['ext-door-galley'].geometry} material={nodes['ext-door-galley'].material} position={[0, 2.021, 0.687]} />
        <mesh name="Object_6" geometry={nodes.Object_6.geometry} material={materials['Scene_-_Root']} position={[0, 0.437, 0.154]} />
        <mesh name="ext_wheel_support_l" geometry={nodes.ext_wheel_support_l.geometry} material={materials['Scene_-_Root']} position={[-1.362, 1.217, 0.868]} />
        <mesh name="ext_shell_l" geometry={nodes.ext_shell_l.geometry} material={nodes.ext_shell_l.material} />
        <mesh name="ext_shell_r" geometry={nodes.ext_shell_r.geometry} material={nodes.ext_shell_r.material}>
          <mesh name="ext_door_inner_r" geometry={nodes.ext_door_inner_r.geometry} material={nodes.ext_door_inner_r.material} position={[1.338, 1.318, -1.116]} rotation={[-Math.PI, 1.202, -Math.PI]}>
            <mesh name="ext_door_window_r" geometry={nodes.ext_door_window_r.geometry} material={nodes.ext_door_window_r.material} position={[-0.043, 0.379, 0.281]} />
          </mesh>
          <mesh name="ext_wheel_support_r" geometry={nodes.ext_wheel_support_r.geometry} material={materials['Scene_-_Root']} position={[1.362, 1.217, 0.868]} />
        </mesh>
        <mesh name="shell_body" geometry={nodes.shell_body.geometry} material={nodes.shell_body.material} />
        <mesh name="roof_rack" geometry={nodes.roof_rack.geometry} material={nodes.roof_rack.material} />
      </group>
    </group>
  )
}

useGLTF.preload('/main.glb')
